services:
   mclogwebviewer:
    container_name: mclogwebviewer
    build: .
    #env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs:ro
      - ./server-icon.png:/server-icon.png:ro